- name: Copy MongoDB yum repo file
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install MongoDB Client
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed

- name: Load {{component}} Schema
  ansible.builtin.shell: mongo --host mongodb-dev.rdevops74.online </app/schema/{{component}}.js