- name: Install Mysql Client
  ansible.builtin.dnf:
    name: mysql
    state: installed

- name: Load {{component}} Schema
  ansible.builtin.shell: mysql -h mysql-dev.rdevops74.online -uroot -pRoboShop@1 < /app/schema/{{component}}.sql
