- name: Install NodeJs repos
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Install NodeJs
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: App Pre requisites
  ansible.builtin.import_tasks: apppreq.yml

- name: Download NodeJS Dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: Schema Setup
  ansible.builtin.import_tasks: mongo-schema.yml
  when: schema is defined

- name: Start {{component}} service
  ansible.builtin.import_tasks: systemd-setup.yml