- name: Create Application User
  ansible.builtin.user:
    name: roboshop

- name: Cleanup Existing Application Content
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create Application Directory
  ansible.builtin.file:
    path: /app
    state: directory

#- name: Download and Extract Application Content
#  ansible.builtin.unarchive:
#    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
#    dest: /app
#    remote_src: yes

- name: Setup Rsyslog Configuration file
  ansible.builtin.template:
    src: "rsyslog.conf"
    dest: /etc/rsyslog.d/roboshop.conf

- name: Start rsyslog Service
  ansible.builtin.systemd:
    name: "rsyslog"
    state: restarted

- name: Download and Extract Application Content From Nexus
  ansible.builtin.unarchive:
    src: http://{{username}}:{{password}}@172.31.35.207:8081/repository/{{component}}/{{component}}-{{appVersion}}.zip
    dest: /app
    remote_src: yes
  vars:
    username: "{{ lookup('amazon.aws.aws_ssm', 'nexus.{{env}}.username', region='us-east-1') }}"
    password: "{{ lookup('amazon.aws.aws_ssm', 'nexus.{{env}}.password', region='us-east-1') }}"
    appVersion: "{{ lookup('amazon.aws.aws_ssm', '{{component}}.{{env}}.appVersion', region='us-east-1') }}"