#- name: Install Maven
#  ansible.builtin.yum:
#    name: maven
#    state: installed

- name: Install Java
  ansible.builtin.yum:
    name: java-17-openjdk
    state: installed

- name: App Pre requisites
  ansible.builtin.import_tasks: apppreq.yml

#- name: Download Java Dependencies
#  ansible.builtin.shell: mvn clean package ; mv target/{{component}}-1.0.jar {{component}}.jar
#  args:
#    chdir: /app

- name: Check DB exists already
  ansible.builtin.shell: echo 'show databases' | mysql -h {{ lookup('amazon.aws.aws_ssm', '{{component}}.{{env}}.DB_HOST', region='us-east-1') }} -u{{ lookup('amazon.aws.aws_ssm', 'rds.{{env}}.master_username', region='us-east-1') }} -p{{ lookup('amazon.aws.aws_ssm', 'rds.{{env}}.master_password', region='us-east-1') }} | grep {{DBNAME}}
  ignore_errors: yes

- name: Schema Setup
  ansible.builtin.import_tasks: mysql-schema.yml
  when: schema is defined

- name: Start {{component}} service
  ansible.builtin.import_tasks: systemd-setup.yml