- name: Install Mysql Client
  ansible.builtin.dnf:
    name: mysql
    state: installed

- name: Load {{component}} Schema
  ansible.builtin.shell: mysql -h {{ lookup('amazon.aws.aws_ssm', 'shipping.{{env}}.DB_HOST', region='us-east-1') }} -uroot -pRoboShop@1 < /app/schema/{{component}}.sql
