- name: Check nodejs is installed
  ansible.builtin.shell: type npm
  register: command_status
  ignore_errors: yes

- name: Install NodeJs repos
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash
  when: command_status.rc != 0

- name: Install NodeJs
  ansible.builtin.yum:
    name: nodejs
    state: installed
  when: command_status.rc != 0

- name: App Pre requisites
  ansible.builtin.import_tasks: apppreq.yml

#- name: Download NodeJS Dependencies
#  ansible.builtin.shell: npm install
#  args:
#    chdir: /app

- name: Schema Setup
  ansible.builtin.import_tasks: mongo-schema.yml
  when: schema is defined

- name: Start {{component}} service
  ansible.builtin.import_tasks: systemd-setup.yml