- name: Build {{component}} Service
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: installed

- name: App Pre requisites
  ansible.builtin.import_tasks: apppreq.yml

- name: Download Python Dependencies
  ansible.builtin.shell: pip3.6 install -r requirements.txt
  args:
    chdir: /app

- name: Start {{component}} service
  ansible.builtin.import_tasks: systemd-setup.yml